### ISSUE TITLE
ssh:fix-key-permissions with custom key

### ISSUE THREAD

**Issue by bravadomizzou** [DeltaSystems/delta-cli-tools#7]
ssh:fix-key-permissions is hardcoded to `/ssh-keys/id_rsa` and ignores what is set with `setSshPrivateKey()` in delta-cli.php.

Eg.
```
$project->createEnvironment('production')
    ->setUsername('deltasys')
    ->setSshPrivateKey(__DIR__.'/ssh-keys/deltasys');
```

**Comment by bravadomizzou** [comment]
I think we will have to use a command for this and not a step.

**Comment by griffbrad** [comment]
I think you'd just add an option to this script:

https://github.com/DeltaSystems/delta-cli-tools/blob/master/library/DeltaCli/Script/SshFixKeyPermissions.php

And the pass that to the step via a new setter.  Can't get the key name from the environment in this case because we're fixing the permissions locally, not on the remote environment.

**Comment by griffbrad** [comment]
In 3.10.1, this step and the associated script will check to see if an environment is selected and then look for the key configured with that environment rather than the default location.  If no environment is specified, it falls back to the default location.
